# Generated by Django 5.2.3 on 2025-07-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Category",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=20)),
                ("price", models.FloatField(default=500)),
                ("description", models.CharField(max_length=500)),
                (
                    "image_url",
                    models.ImageField(default="abc.jpg", upload_to="media/Images/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AdminApp.category",
                    ),
                ),
            ],
            options={
                "db_table": "Book",
            },
        ),
    ]
