# Generated by Django 5.2.3 on 2025-07-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "UserInfo",
            },
        ),
    ]
