# Generated by Django 5.2.3 on 2025-07-31 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0002_book_author"),
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField(default=2)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AdminApp.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserApp.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "MyCart",
            },
        ),
    ]
